services:

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u root -p$$SQL_ROOT_PASSWORD -h localhost --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception:
    driver: bridge

volumes:

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
